/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-01-24 05:55:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#datepicker\").datepicker();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호 동일 체크 이벤트\r\n");
      out.write("\t\t$('#signUpPwCk').keyup(function(){\r\n");
      out.write("\t\t\tvar result = \"\";\r\n");
      out.write("\t\t\tvar pw = $('#signUpPw').val();\r\n");
      out.write("\t\t\tvar pw2 = $('#signUpPwCk').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pw == pw2){\r\n");
      out.write("\t\t\t\tresult = \"Match!\";\r\n");
      out.write("\t\t\t\t$('#pwch').css('padding-top','1em');\r\n");
      out.write("\t\t\t\t$('#pwch').css('color','green');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tresult = \"Not Match!\";\r\n");
      out.write("\t\t\t\t$('#pwch').css('padding-top','4px');\r\n");
      out.write("\t\t\t\t$('#pwch').css('color','red');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#pwch').html(result);\t\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"small-dialog\" class=\"mfp-hide w3ls_small_dialog\">\r\n");
      out.write("\t<h2>로그인</h2>\r\n");
      out.write("\t<div class=\"modal-body agileits_modal_body\">\r\n");
      out.write("\t\t<form action=\"loginCheck.do\" method=\"post\">\r\n");
      out.write("\t\t\t<span><input type=\"text\" name=\"id\"\r\n");
      out.write("\t\t\t\tplaceholder=\"아이디\" required />\r\n");
      out.write("\t\t\t</span> <span class=\"w3_modal\"><input type=\"password\" name=\"pw\"\r\n");
      out.write("\t\t\t\tplaceholder=\"비밀번호\" required />\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<div class=\"agile_remember\">\r\n");
      out.write("\t\t\t\t<div class=\"agile_remember_left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"check\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"checkbox\"><i> </i>아이디 저장하기</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"agile_remember_right\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<h5>\r\n");
      out.write("\t\t\t계정이 없으신가요? \r\n");
      out.write("\t\t\t\t<a href=\"#small-dialog1\"\r\n");
      out.write("\t\t\t\tclass=\"play-icon popup-with-zoom-anim\">회원가입</a>\r\n");
      out.write("\t\t</h5>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"small-dialog1\" class=\"mfp-hide\">\r\n");
      out.write("\t<h2>회원가입</h2>\r\n");
      out.write("\t<div class=\"modal-body w3_agileits_modal_body\">\r\n");
      out.write("\t\t<form action=\"signUp.do\" method=\"post\" name=\"vForm\">\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>아이디</span><input id=\"idCheck1\" style=\"padding:10px;font-size:14px;display:inline-block;float:left; type=\"text\" name=\"ID\" required autofocus/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"중복확인\" id=\"id_check\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>비밀번호</span> <input id=\"signUpPw\" type=\"password\" name=\"Password\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>재확인</span> <input style=\"display:inline-block;float:left;\" id=\"signUpPwCk\" type=\"password\" name=\"Password-check\" required />\r\n");
      out.write("\t\t\t\t<span id=\"pwch\" style=\"font-size:9pt;display:block;\">&nbsp;</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>지역</span> <input type=\"text\" name=\"Region\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>Email</span> <input type=\"email\" name=\"Email\" required />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"w3_modal_body_grid w3_modal_body_grid1\">\r\n");
      out.write("\t\t\t\t<span>팀코드</span> <input type=\"text\" name=\"team_code\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Sign Up\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<h5>\r\n");
      out.write("\t\t\t이미 회원이십니까? <a href=\"#small-dialog\"\r\n");
      out.write("\t\t\t\tclass=\"play-icon popup-with-zoom-anim\">로그인</a>\r\n");
      out.write("\t\t</h5>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
