/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-01-23 04:38:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.versus.dto.InputMemberInfoDto;
import com.versus.dto.MatchDto;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


	InputMemberInfoDto dto;
	MatchDto match_dtos;
	String id;
	String nickName;
	int teamCode;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Matchmaking a Mobile App Flat Bootstrap Responsive\r\n");
      out.write("\tWebsite Template | Main :: W3layouts</title>\r\n");
      out.write("<!-- For-Mobile-Apps-and-Meta-Tags -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("\tcontent=\"Matchmaking Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, SmartPhone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design\" />\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"js/bootstrap.js\"></script> -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<!-- //For-Mobile-Apps-and-Meta-Tags -->\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<link href=\"style.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel='stylesheet' id='fluid_dg-css' href='css/fluid_dg.css'\r\n");
      out.write("\ttype='text/css' media='all'>\r\n");
      out.write("<link href=\"css/popuo-box.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!-- //Custom Theme files -->\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Monoton\" rel=\"stylesheet\">\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type='text/javascript' src='js/jquery-2.2.3.min.js'></script>\r\n");
      out.write("<!-- 다음지도 api -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"//apis.daum.net/maps/maps3.js?apikey=9978627f24a383749e985ea4d7323101\"></script> -->\r\n");
      out.write("<!-- //js -->\r\n");
      out.write("<!-- web-fonts -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Courgette'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- //web-fonts -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write('\r');
      out.write('\n');

	if(request.getAttribute("memberInfo")!= null){
		session.setAttribute("memberInfo",request.getAttribute("memberInfo"));
		dto = (InputMemberInfoDto)request.getAttribute("memberInfo") ;
		teamCode = dto.getTeamCode();
		session.setAttribute("teamCode",teamCode);
		nickName = dto.getNickName();
		session.setAttribute("nickName",nickName);
		id = dto.getId();
		session.setAttribute("id",id);
		System.out.println("로그인후 세션에 정보 저장!");
	}
	if(request.getAttribute("logout") != null){
		if((String)request.getAttribute("logout") == "logout"){
			session.setAttribute("memberInfo",null);
			System.out.println("세션의 정보 삭제");
		}
	}

      out.write("\r\n");
      out.write("<body class=\"bg\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "login.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "maketeam.jsp", out, true);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "makematch.jsp", out, true);
      out.write("\r\n");
      out.write("\t<div class=\"nav-container hidden hideNav w3_nav\">\r\n");
      out.write("\t\t<ul class=\"nav-list\">\r\n");
      out.write("\t\t\t<li class=\"list-item active\"><a href=\"main.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-home\"></i></a></li>\r\n");
      out.write("\t\t\t<li class=\"list-item\"><a href=\"matchstatus.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-info-sign\" ></i></a></li>\r\n");
      out.write("\t\t\t<li class=\"list-item\"><a href=\"info.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-cog\"></i></a></li>\r\n");
      out.write("\t\t\t<li class=\"list-item\"><a href=\"faq.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-text-size\" ></i></a></li>\r\n");
      out.write("\t\t\t<li class=\"list-item\"><a href=\"#make-team\" class=\"popup-with-zoom-anim\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i></a></li>\r\n");
      out.write("\t\t\t<li class=\"list-item\"><a href=\"#make_match\" class=\"popup-with-zoom-anim\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-envelope\"></i></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"ban\" class=\"agileinfo_menu w3l_menu\">\r\n");
      out.write("\t\t<button class=\"btn-nav w3layouts_btn\">\r\n");
      out.write("\t\t\t<img src=\"images/nav-icon.png\" width=\"30px\" height=\"25px\">\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"agileinfo_menu_center\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"main.jsp\"><span id=\"mainV\">V</span>ersus<span>For Exciting <i>Matches</i></span></a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"agileinfo_menu_right\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t");

				if( session.getAttribute("memberInfo") == null){
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#small-dialog\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"play-icon popup-with-zoom-anim\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"images/login.png\" width=\"35px\" height=\"35px\"></a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
 }else{
      out.write(" \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"info_id\"><a href=\"logout.do?nowPage=main.jsp\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></div>\r\n");
      out.write("\t\t\t\t\t\t<!-- <img src=\"images/close.png\" width=\"30px\" height=\"30px\"> -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<div class=\"banner-bottom-login\">\r\n");
      out.write("\t\t\t<div class=\"w3agile_banner_btom_login\">\r\n");
      out.write("\t\t\t\t<form action=\"searchMatch.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3agile__text w3agile_banner_btom_login_left city\">\r\n");
      out.write("\t\t\t\t\t\t<h4>지역</h4>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"frm-field required country choice_region1\" name=\"region1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">선택</option><option value=\"서울\">서울</option><option value=\"경기\">경기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"인천\">인천</option><option value=\"강원\">강원</option><option value=\"광주\">광주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"충북\">충북</option><option value=\"충남\">충남</option><option value=\"대구\">대구</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"대전\">대전</option><option value=\"경북\">경북</option><option value=\"경남\">경남</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"울산\">울산</option><option value=\"전북\">전북</option><option value=\"전남\">전남</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"제주\">제주</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3agile__text w3agile_banner_btom_login_left city city2\">\r\n");
      out.write("\t\t\t\t\t\t<h4>지역2</h4>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"frm-field required country choice_region2\" name=\"region2\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3agile__text w3agile_banner_btom_login_left2\">\r\n");
      out.write("\t\t\t\t\t\t<h4>날짜</h4>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"search_month\" class=\"selOpt\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">월</option><option value=\"1\">1</option><option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option><option value=\"4\">4</option><option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option><option value=\"7\">7</option><option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option><option value=\"10\">10</option><option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"search_day\" class=\"selOpt\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">일</option><option value=\"1\">1</option><option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option><option value=\"4\">4</option><option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">6</option><option value=\"7\">7</option><option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"9\">9</option><option value=\"10\">10</option><option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"12\">12</option><option value=\"13\">13</option><option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"15\">15</option><option value=\"16\">16</option><option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"18\">18</option><option value=\"19\">19</option><option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"21\">21</option><option value=\"22\">22</option><option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"24\">24</option><option value=\"25\">25</option><option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"27\">27</option><option value=\"28\">28</option><option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30</option><option value=\"31\">31</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<!-- <input type=\"date\" name=\"start_date\" id=\"start_date\" name=\"date\"> -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3agile__text w3agile_banner_btom_login_left1\">\r\n");
      out.write("\t\t\t\t\t\t<h4>시간</h4>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"country1\" class=\"frm-field required time1\" name=\"time1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">시</option><option value=\"00\">00</option><option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"02\">02</option><option value=\"03\">03</option><option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"05\">05</option><option value=\"06\">06</option><option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"08\">08</option><option value=\"09\">09</option><option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\">11</option><option value=\"12\">12</option><option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"14\">14</option><option value=\"15\">15</option><option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"17\">17</option><option value=\"18\">18</option><option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20</option><option value=\"21\">21</option><option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"23\">23</option><option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <span>~</span> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"country2\" class=\"frm-field required time2\" name=\"time2\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">시</option><option value=\"00\">00</option><option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"02\">02</option><option value=\"03\">03</option><option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"05\">05</option><option value=\"06\">06</option><option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"08\">08</option><option value=\"09\">09</option><option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"11\">11</option><option value=\"12\">12</option><option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"14\">14</option><option value=\"15\">15</option><option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"17\">17</option><option value=\"18\">18</option><option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"20\">20</option><option value=\"21\">21</option><option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"23\">23</option><option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"submit_center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"image\" name=\"submit\" src=\"images/find.png\" border=\"0\" width=\"20px\" height=\"20px\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"submit_button\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"find_dropdown\">\r\n");
      out.write("\t\t\t<div class=\"find_button\">\r\n");
      out.write("\t\t\t\t<a data-toggle=\"collapse\" href=\"#collapse1\" id=\"find_button\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/find.png\" id=\"find_button\" width=\"20px\" height=\"20px\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery.magnific-popup.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<div class=\"banner-bottom\" id=\"moveup\">\r\n");
      out.write("\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /web/main.jsp(209,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        // /web/main.jsp(209,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("MatchDto");
        // /web/main.jsp(209,2) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVarStatus("MatchStatus");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t<div class=\"information\">\r\n");
              out.write("\t\t\t\t<a href=\"#team_information");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchStatus.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\" class=\"team_information play-icon popup-with-zoom-anim\">\r\n");
              out.write("\t\t\t\t\t<div class=\"team_progress\">\r\n");
              out.write("\t\t\t\t\t\t<div class=\"progress_circle progress_green\"></div>\r\n");
              out.write("\t\t\t\t\t\t<div class=\"progress_circle progress_yellow\"></div>\r\n");
              out.write("\t\t\t\t\t\t<div class=\"progress_circle progress_red\"></div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t<div class=\"team_info\">\r\n");
              out.write("\t\t\t\t\t\t<div class=\"team_mark\">\r\n");
              out.write("\t\t\t\t\t\t\t<p>\r\n");
              out.write("\t\t\t\t\t\t\t\t<b>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.team_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</b>\r\n");
              out.write("\t\t\t\t\t\t\t<p>\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t<div class=\"placeinfo\">\r\n");
              out.write("\t\t\t\t\t\t\t<p>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</p>\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t<div class=\"date_con\">\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"dateinfo\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<p>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_c_005fforTokens_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</p>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"timeinfo\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<p>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              if (_jspx_meth_c_005fforTokens_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</p>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t</a>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t\t<div id=\"team_information");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchStatus.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\" class=\"team_information mfp-hide w3ls_small_dialog\">\r\n");
              out.write("\t\t\t\t<h2>경기 정보</h2>\r\n");
              out.write("\t\t\t\t<div class=\"modal-body agileits_modal_body\">\r\n");
              out.write("\t\t\t\t<form action=\"#\">\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_name\">팀이름 : </span><span class=\"teamdata\" id=\"teamdata_name1\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.team_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_place\">장소 : </span><span class=\"teamdata\" id=\"teamdata_place1\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_date\">일시 : </span><span class=\"teamdata\" id=\"teamdata_date1\">\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fforTokens_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t</span><br>\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_level\">팀정보 : </span><span class=\"teamdata\" id=\"teamdata_level1\">Lv ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(',');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.win}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write('승');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.lose}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write('패');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.draw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("무, \r\n");
              out.write("\t\t\t\t\t\t경고횟수: ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.penalty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_phone\">연락처 : </span><span class=\"teamdata\" id=\"teamdata_phone1\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t<span class=\"teamdata\" id=\"teamdata_uniform\">유니폼색상 : </span><span class=\"teamdata\" id=\"teamdata_uniform1\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.uniform}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t<div class=\"teamdata_con\">\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t");
              if (_jspx_meth_c_005fchoose_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t<span>- 상세정보 -</span><br>\r\n");
              out.write("\t\t\t\t\t<span id=\"teamdata_more\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.more_info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t<div class=\"teamdata_con\">\r\n");
              out.write("\t\t\t\t\t\t<div id=\"teamdata_map\">\r\n");
              out.write("\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t");
if((session.getAttribute("memberInfo")==null)||((Integer)session.getAttribute("teamCode")==0)){
						
              out.write("<a href=\"#make_match\" class=\"apply_error popup-with-zoom-anim\">신청하기</a>");

					}else{
						
              out.write("<input type=\"submit\" value=\"신청하기\">");

					} 
              out.write(" \r\n");
              out.write("\t\t\t\t\t");
              if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t</form>\r\n");
              out.write("\t\t\t\t</div>\r\n");
              out.write("\t\t\t</div>\r\n");
              out.write("\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!-- 경기 정보 -->\r\n");
      out.write("\t\t<!-- 경기 만들기 -->\r\n");
      out.write("\t\t<div class=\"footer_nav\">\r\n");
      out.write("\t\t\t<!-- <div class=\"ft_con\"> -->\r\n");
      out.write("\t\t\t\t<div class=\"ft_nav1\"><a href=\"main.jsp\"><img src=\"images/matching.png\" width=\"40px\" height=\"40px\"></a></div>\r\n");
      out.write("\t\t\t\t<div class=\"ft_nav2\"><a href=\"matchstatus.jsp\"><img src=\"images/status.png\" width=\"40px\" height=\"40px\"></a></div>\r\n");
      out.write("\t\t\t\t<div class=\"ft_nav3\"><a href=\"info.jsp\"><img src=\"images/teamInfo.png\" width=\"40px\" height=\"40px\"></a></div>\r\n");
      out.write("\t\t\t\t<div class=\"ft_nav4\"><a href=\"faq.jsp\"><img src=\"images/qna.png\" width=\"40px\" height=\"40px\"></a></div>\r\n");
      out.write("\t\t\t<!-- </div> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer-pos\">\r\n");
      out.write("\t\t\t<a href=\"#make_match\" class=\"play-icon popup-with-zoom-anim\"><span></span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //footer -->\r\n");
      out.write("\t<!-- banner -->\r\n");
      out.write("\t<script type='text/javascript' src='js/jquery.easing.1.3.js'></script>\r\n");
      out.write("\t<script type='text/javascript' src='js/fluid_dg.min.js'></script>\r\n");
      out.write("\t<script type='text/javascript' src='js/versus.js' charset=\"utf-8\"></script>\r\n");
      out.write("\t<!-- //banner -->\r\n");
      out.write("\t<!-- nav -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t//지역별 검색옵션 이벤트\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar seoul = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\r\n");
      out.write("\t\t\t\t\t\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\r\n");
      out.write("\t\t\t\t\t\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("\t\tvar keongki = [\"가평군\", \"고양시\", \"과천시\", \"광명시\", \"광주시\", \"구리시\", \"군포시\", \"김포시\",\r\n");
      out.write("\t\t\t\t\t\t\"남양주\", \"동두천\", \"부천시\", \"성남시\", \"수원시\", \"시흥시\", \"안산시\", \"안성시\",\r\n");
      out.write("\t\t\t\t\t\t\"안양시\", \"양주시\", \"양평군\", \"여주군\", \"연천군\", \"오산시\", \"용인시\", \"의왕시\",\r\n");
      out.write("\t\t\t\t\t\t\"의정부\", \"이천시\", \"파주시\", \"평택시\", \"포천시\", \"하남시\", \"화성시\"];\r\n");
      out.write("\t\tvar incheon = [\"강화군\",\"계양구\", \"남구\",\"남동구\", \"동구\",\"부평구\", \"서구\",\"연수구\", \"웅진군\", \"중구\"];\r\n");
      out.write("\t\tvar gangwon = [\"강릉시\",\"고성군\",\"동해시\",\"삼척시\",\"속초시\",\"양구군\",\"양양군\",\"영월군\",\"원주시\",\"인제군\",\r\n");
      out.write("\t\t\t\t\t\t\"정선군\",\"철원군\",\"춘천시\",\"태백시\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("\t\tvar keongbuk = [\"경산시\", \"경주시\", \"고령군\", \"구미시\", \"군위군\", \r\n");
      out.write("\t\t\t\t\t\t\"김천시\", \"문경시\", \"봉화군\", \"상주시\", \"성주군\", \r\n");
      out.write("\t\t\t\t\t\t\"안동시\", \"영덕군\", \"영양군\", \"영주시\", \"영천시\", \r\n");
      out.write("\t\t\t\t\t\t\"예천군\", \"울릉군\", \"울진군\", \"의성군\", \"청도군\", \r\n");
      out.write("\t\t\t\t\t\t\"청송군\", \"칠곡군\", \"포항시\"];\r\n");
      out.write("\t\tvar keongnam = [\"거제시\", \"거창군\", \"고성군\", \"김해시\", \r\n");
      out.write("\t\t\t\t\t\t\"남해군\", \"마산시\", \"밀양시\", \"사천시\",\r\n");
      out.write("\t\t\t\t\t\t\"산청군\", \"양산시\", \"의령군\", \"진주시\", \r\n");
      out.write("\t\t\t\t\t\t\"진해시\", \"창년군\", \"창원시\", \"통영시\",\r\n");
      out.write("\t\t\t\t\t\t\"하동군\", \"함안군\", \"함양군\", \"합천군\"];\r\n");
      out.write("\t\tvar gwangju = [\"광산구\", \"남구\",\"동구\",\"북구\",\"서초구\"];\r\n");
      out.write("\t\tvar daegu = [\"남구\",\"달서구\",\"달성군\", \"동구\",\"북구\",\"서구\",\"수성구\", \"중구\"];\r\n");
      out.write("\t\tvar daejeon = [\"대덕구\", \"동구\",\"서구\",\"유성구\", \"중구\"];\r\n");
      out.write("\t\tvar busan = [\"강서구\", \"금정구\", \"기장군\", \"남구\",\r\n");
      out.write("\t\t\t\t\t\"동구\", \"동래구\", \"부산진구\", \"북구\", \r\n");
      out.write("\t\t\t\t\t\"사상구\", \"사하구\", \"서구\", \"수영구\", \r\n");
      out.write("\t\t\t\t\t\"연제구\", \"영도구\", \"중구\", \"해운대\"];\r\n");
      out.write("\t\tvar ulsan = [\"중구\",\"남구\", \"동구\",\"북구\",\"울주군\"];\r\n");
      out.write("\t\tvar jeonnam = [\"강진군\", \"고흥군\", \"곡성군\", \"광양시\", \r\n");
      out.write("\t\t\t\t\t\t\"구례군\", \"나주시\", \"담양군\", \"목포시\", \r\n");
      out.write("\t\t\t\t\t\t\"무안군\", \"보성군\", \"순천시\", \"신안군\", \r\n");
      out.write("\t\t\t\t\t\t\"여수시\", \"영광군\", \"영암군\", \"완도군\", \r\n");
      out.write("\t\t\t\t\t\t\"정성군\", \"장흥군\", \"진도군\", \"함평군\", \r\n");
      out.write("\t\t\t\t\t\t\"해남군\", \"화순군\"];\r\n");
      out.write("\t\tvar jeonbuk = [\"고창군\", \"군산시\", \"김제시\", \"남원시\", \r\n");
      out.write("\t\t\t\t\t\t\"무주군\", \"부안군\", \"순찬군\", \"완주군\", \r\n");
      out.write("\t\t\t\t\t\t\"익산시\", \"임실군\", \"장수군\", \"전주시\", \r\n");
      out.write("\t\t\t\t\t\t\"정읍시\", \"진안군\"];\r\n");
      out.write("\t\tvar jeju = [\"서귀포시\", \"제주시\"];\r\n");
      out.write("\t\tvar chungnam = [\"공주시\", \"금산군\", \"논산시\", \"당진군\",\r\n");
      out.write("\t\t\t\t\t\t\"보령시\", \"부여군\", \"서산시\", \"서천군\",\r\n");
      out.write("\t\t\t\t\t\t\"아산시\", \"연기군\", \"예산군\", \"천안시\", \r\n");
      out.write("\t\t\t\t\t\t\"청양군\", \"태안군\", \"홍성군\", \"계룡시\"];\r\n");
      out.write("\t\tvar chungbuk = [\"괴산군\", \"단양군\", \"보은군\", \"영동군\", \r\n");
      out.write("\t\t\t\t\t\t\"옥천군\", \"음성군\", \"제천시\", \"전천군\", \r\n");
      out.write("\t\t\t\t\t\t\"창원군\", \"청주시\", \"충주시\", \"증평군\"];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.choice_region1').on(\"change\", function(){\r\n");
      out.write("\t\t\tvar region = $(this).val();\r\n");
      out.write("\t\t\t$('.choice_region2').empty();\r\n");
      out.write("\t\t\t$('.choice_region2').append('<option value=\"\">선택</option>');\r\n");
      out.write("\t\t\tswitch(region){\r\n");
      out.write("\t\t\t\tcase \"서울\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<seoul.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+seoul[i]+'>' + seoul[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"경기\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<keongki.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+keongki[i]+'>' + keongki[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"인천\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<incheon.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+incheon[i]+'>' + incheon[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"강원\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<gangwon.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+gangwon[i]+'>' + gangwon[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"광주\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<gwangju.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+gwangju[i]+'>' + gwangju[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"충북\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<chungbuk.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+chungbuk[i]+'>' + chungbuk[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"충남\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<chungnam.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+chungnam[i]+'>' + chungnam[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"대구\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<daegu.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+daegu[i]+'>' + daegu[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"대전\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<daejeon.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+daejeon[i]+'>' + daejeon[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"경북\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<keongbuk.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+keongbuk[i]+'>' + keongbuk[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"경남\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<keongnam.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+keongnam[i]+'>' + keongnam[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"울산\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<ulsan.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+ulsan[i]+'>' + ulsan[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"전북\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<jeonbuk.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+jeonbuk[i]+'>' + jeonbuk[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"전남\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<jeonnam.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+jeonnam[i]+'>' + jeonnam[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"제주\":\r\n");
      out.write("\t\t\t\t\tfor(i=0; i<jeju.length; i++){\r\n");
      out.write("\t\t\t\t\t\t$('.choice_region2').append('<option value='+jeju[i]+'>' + jeju[i] + '</option>');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //nav -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforTokens_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    try {
      _jspx_th_c_005fforTokens_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /web/main.jsp(229,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setVar("YMD");
      // /web/main.jsp(229,9) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setItems((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /web/main.jsp(229,9) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setDelims(" ");
      // /web/main.jsp(229,9) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setBegin(0);
      // /web/main.jsp(229,9) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setEnd(0);
      int[] _jspx_push_body_count_c_005fforTokens_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f0 = _jspx_th_c_005fforTokens_005f0.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${YMD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin.reuse(_jspx_th_c_005fforTokens_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforTokens_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    try {
      _jspx_th_c_005fforTokens_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /web/main.jsp(236,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setVar("HMS");
      // /web/main.jsp(236,9) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setItems((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /web/main.jsp(236,9) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setDelims(" ");
      // /web/main.jsp(236,9) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setBegin(1);
      // /web/main.jsp(236,9) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f1.setEnd(1);
      int[] _jspx_push_body_count_c_005fforTokens_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f1 = _jspx_th_c_005fforTokens_005f1.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforTokens_005f2(_jspx_th_c_005fforTokens_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforTokens_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvar_005fitems_005fend_005fdelims_005fbegin.reuse(_jspx_th_c_005fforTokens_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforTokens_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforTokens_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforTokens_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    try {
      _jspx_th_c_005fforTokens_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforTokens_005f1);
      // /web/main.jsp(237,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setVar("HM");
      // /web/main.jsp(237,10) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setItems((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HMS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /web/main.jsp(237,10) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setDelims(":");
      // /web/main.jsp(237,10) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setBegin(0);
      // /web/main.jsp(237,10) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setEnd(1);
      // /web/main.jsp(237,10) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f2.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforTokens_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f2 = _jspx_th_c_005fforTokens_005f2.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforTokens_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforTokens_005f2))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f2.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin.reuse(_jspx_th_c_005fforTokens_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforTokens_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforTokens_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforTokens_005f2);
      // /web/main.jsp(238,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count == 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          out.write(':');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforTokens_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    try {
      _jspx_th_c_005fforTokens_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /web/main.jsp(254,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setVar("HM");
      // /web/main.jsp(254,6) name = items type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setItems((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.match_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /web/main.jsp(254,6) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setDelims(":");
      // /web/main.jsp(254,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setBegin(0);
      // /web/main.jsp(254,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setEnd(1);
      // /web/main.jsp(254,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f3.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforTokens_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f3 = _jspx_th_c_005fforTokens_005f3.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${HM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforTokens_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforTokens_005f3))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f3.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fvarStatus_005fvar_005fitems_005fend_005fdelims_005fbegin.reuse(_jspx_th_c_005fforTokens_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforTokens_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforTokens_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforTokens_005f3);
      // /web/main.jsp(255,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count == 1}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          out.write(':');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /web/main.jsp(264,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.shower == '1'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"shower\">샤워실");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"shower\" checked>샤워실");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /web/main.jsp(268,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.parking == '1'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"parking\">주차장");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"parking\" checked>주차장");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /web/main.jsp(272,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.neon == '1'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"neon\">전광판");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"neon\" checked>전광판");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f3 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f3 = _jspx_th_c_005fchoose_005f3.doStartTag();
      if (_jspx_eval_c_005fchoose_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f3(_jspx_th_c_005fchoose_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f3);
      // /web/main.jsp(276,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MatchDto.whistle == '1'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"whistle\">호루라기");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f3 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    try {
      _jspx_th_c_005fotherwise_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f3);
      int _jspx_eval_c_005fotherwise_005f3 = _jspx_th_c_005fotherwise_005f3.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<input type=\"checkbox\" disabled value=\"whistle\" checked>호루라기");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /web/main.jsp(291,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${matchComment}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /web/main.jsp(291,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("Comment");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t<table id=\"commentTable\" class=\"table table-condensed\"></table>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
