/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2017-01-21 11:37:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.versus.dto.InputMemberInfoDto;

public final class makematch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<div id=\"make_match\" class=\"mfp-hide w3ls_small_dialog\">\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
		if (session.getAttribute("memberInfo") == null) {
      out.write("\r\n");
      out.write("\t\t\t<h2>먼저 로그인해야 합니다.</h2>\r\n");
      out.write("\t\t\t<a href=\"#small-dialog\" class=\"play-icon popup-with-zoom-anim\">로그인하러 가기</a>\r\n");
      out.write("\t");
} else if ((Integer)session.getAttribute("teamCode") == 0) {
      out.write("\r\n");
      out.write("\t\t\t<h2>소속된 팀이 없습니다.</h2>\r\n");
      out.write("\t\t\t<a href=\"#make-team\" class=\"play-icon popup-with-zoom-anim\">팀 만들러 가기</a>\r\n");
      out.write("\t");
} else { 
      out.write("\r\n");
      out.write("\t<h2>경기 만들기</h2>\r\n");
      out.write("\t<div class=\"modal-body agileits_modal_body team\">\r\n");
      out.write("\t\t<form action=\"makeMatch.do\" method=\"post\" class=\"form-inline\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"teamCode\" value=\"");
      out.print((Integer)session.getAttribute("teamCode"));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"nickName\" value=\"");
      out.print((String)session.getAttribute("nickName"));
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print((String)session.getAttribute("id"));
      out.write("\">\r\n");
      out.write("\t\t\t<label for=\"region1\">장소</label>\r\n");
      out.write("\t\t\t<select id=\"choice_region1\" class=\"frm-field required choice_region1 make_input\" name=\"region1\">\r\n");
      out.write("\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t<option value=\"서울\">서울</option>\r\n");
      out.write("\t\t\t\t<option value=\"경기\">경기</option>\r\n");
      out.write("\t\t\t\t<option value=\"인천\">인천</option>\r\n");
      out.write("\t\t\t\t<option value=\"강원\">강원</option>\r\n");
      out.write("\t\t\t\t<option value=\"광주\">광주</option>\r\n");
      out.write("\t\t\t\t<option value=\"충북\">충북</option>\r\n");
      out.write("\t\t\t\t<option value=\"충남\">충남</option>\r\n");
      out.write("\t\t\t\t<option value=\"대구\">대구</option>\r\n");
      out.write("\t\t\t\t<option value=\"대전\">대전</option>\r\n");
      out.write("\t\t\t\t<option value=\"경북\">경북</option>\r\n");
      out.write("\t\t\t\t<option value=\"경남\">경남</option>\r\n");
      out.write("\t\t\t\t<option value=\"울산\">울산</option>\r\n");
      out.write("\t\t\t\t<option value=\"전북\">전북</option>\r\n");
      out.write("\t\t\t\t<option value=\"전남\">전남</option>\r\n");
      out.write("\t\t\t\t<option value=\"제주\">제주</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<select id=\"choice_region2\" class=\"frm-field required choice_region2 make_input\" name=\"region2\">\r\n");
      out.write("\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t</select><br>\r\n");
      out.write("\t\t\t<label for=\"match_place\">세부장소</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"match_place\" name=\"match_place\" class=\"make_input\" autofocus required><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label for=\"month\">일시</label>\r\n");
      out.write("\t\t\t<select name=\"month\" id=\"month\" class=\"selOpt1\">\r\n");
      out.write("\t\t\t\t<option value=\"\">월</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<select name=\"day\" class=\"selOpt1\">\r\n");
      out.write("\t\t\t\t<option value=\"\">일</option>\r\n");
      out.write("\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<select name=\"hour\" class=\"selOpt1\">\r\n");
      out.write("\t\t\t\t<option value=\"\">시</option>\r\n");
      out.write("\t\t\t\t<option value=\"00\">00</option>\r\n");
      out.write("\t\t\t\t<option value=\"01\">01</option>\r\n");
      out.write("\t\t\t\t<option value=\"02\">02</option>\r\n");
      out.write("\t\t\t\t<option value=\"03\">03</option>\r\n");
      out.write("\t\t\t\t<option value=\"04\">04</option>\r\n");
      out.write("\t\t\t\t<option value=\"05\">05</option>\r\n");
      out.write("\t\t\t\t<option value=\"06\">06</option>\r\n");
      out.write("\t\t\t\t<option value=\"07\">07</option>\r\n");
      out.write("\t\t\t\t<option value=\"08\">08</option>\r\n");
      out.write("\t\t\t\t<option value=\"09\">09</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<label for=\"match_phone\">연락처</label><input type=\"text\" name=\"match_phone\" class=\"make_input\" required><br> \r\n");
      out.write("\t\t\t<label for=\"match_uniform\">유니폼색상</label><input type=\"text\" name=\"match_uniform\" class=\"make_input\"><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"teamdata_con\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"shower\" value=\"1\">샤워실 \r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"parking\" value=\"1\">주차장 \r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"neon\" value=\"1\">전광판 \r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"whistle\" value=\"1\">호루라기\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span>- 상세정보 -</span>\r\n");
      out.write("\t\t\t<textarea name=\"match_more\" class=\"make_input\" style=\"resize: none; width: 100%;\"></textarea><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"teamdata_con\">\r\n");
      out.write("\t\t\t\t<div id=\"teamdata_map\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"만들기\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
